development:
  adapter: postgresql
  encoding: unicode
  database: ecc_development
  pool: 5
  host: localhost
  username: mauriciovoto

test:
  adapter: postgresql
  encoding: unicode
  database: ecc_test
  pool: 5
  host: localhost
  username: mauriciovoto

production:
  adapter: postgresql
  encoding: unicode
  database: ecc_production
  pool: 5
  host: localhost
  username: mauriciovoto